### ISSUE TITLE
行のハッシュ名をdata1, data2... ではなく特定のハッシュ名の配列として扱いたい

### ISSUE THREAD

**Issue by enpel** [seed-ui/seedtable#22]
はじめまして、業務でExcelのデータをYAMLに変換する必要がありseedtableに行き着きました。
早速使ってみたのですが、行毎のハッシュがdata1,data2....だと少々扱いづらいのでもし可能でしたら指定したハッシュ名の配列として使いたいです。

合間で自分の方でも対応出来ないか調べようとは思うのでもし対応できそうであれば教えていただければ幸いです。
以上、よろしくお願いします。

**Comment by Narazaka** [comment]
> 指定したハッシュ名の配列

というのは

```
data1:
  id: 1
  name: a
data2:
  id: 2
  name: b
```

ではなく

```
- id: 1
  name: a
- id: 2
  name: b
```

という感じのことでしょうか？

あるいは

```
特定の名前:
  - id: 1
    name: a
  - id: 2
    name: b
```

でしょうか。

**Comment by enpel** [comment]
どちらかというと自分のイメージは下記の方です。
```
特定の名前:
  - id: 1
    name: a
  - id: 2
    name: b
```

**Comment by Narazaka** [comment]
（特定の名前）っていうのがぽっと出な感じはあるので、やるとすれば

```
- id: 1
  name: a
- id: 2
  name: b
```

にするのが妥当かと思いました。

読み込み時に

```
foo.yml:
  - id: 1
    name: a
  - id: 2
    name: b
```

みたいな構造にしていただくって感じで。
